### ISSUE TITLE
Github outdated

### ISSUE THREAD

**Issue by Pijuli** [Aladex/softethervpn-docker#1]
Hi!
I guess you are the one behind https://hub.docker.com/r/aladex/softethervpn_client

Would it be possible to update the repo? I see you are updating docker hub but not the sources. Also a link there to the repo would be awesome.

Thank you!!

**Comment by Aladex** [comment]
Hey! This isn't an official repository. If you need the source code, it's in the official repository: https://github.com/SoftEtherVPN/SoftEtherVPN  
I'm just building these images, checking if there's a new commit or tag in the branch. The build runs on my local Jenkins.  
I didn't think anyone else would need this repo besides me, but I'll add a link to the official repo in the README. Thanks.

**Comment by Pijuli** [comment]
I know its not the source code! :) but I thought your files were not updated. I guess they are!
Yet, thank you for the builds!
